INSERT INTO translations (id, fr, en, error_key)
VALUES (DEFAULT,
        'Cette Tripel forte (8,4%) est brassée avec de l''orge, du blé et de l''avoine. C''est une bière parfaitement équilibrée qui est délicieuse à déguster avec de nombreux types de fromages, notamment avec du brie crémeux',
        'This strong Tripel (8.4%) is brewed with barley, wheat and oats. It’s a perfectly balanced beer that’s delicious to taste with many types of cheeses, especially with creamy brie.',
        null),

       (DEFAULT,
        'Cette bière d''abbaye spéciale a une délicate mousse blanche et un goût doux et riche. La levure typique d''Affligem donne une belle touche fruitée à notre blonde la plus vendue',
        'This special abbey beer has delicate white head and soft, rich taste. The typical Affligem yeast gives a nice, fruity touch to our best-selling Blond.',
        null),

       (DEFAULT,
        'Vous êtes fan de Tripels, mais moins de bières brunes ? Laissez-vous convaincre par la reine de Chimay ! Le malt foncé reste subtil, vous le goûterez sous forme de caramel et de toffee.',
        'Are you a fan of Tripels, but less so into dark beers? Let yourself be convinced by the king of Chimay! The dark malt remains subtle; you’ll taste it in the form of caramel and toffee.',
        null),

       (DEFAULT,
        'Avec un taux d''alcool de 8,5 %, la Duvel est une bière belge typique. L''alcool lui donne de la douceur, tandis que les variétés de houblon Saaz et Styrian Golding lui confèrent un caractère fruité et orangé.',
        'With an alcohol percentage of 8.5%, Duvel is a typical Belgian powerhouse. The alcohol gives it sweetness, while the hop varieties Saaz and Styrian Golding provide a fruity, orangey character',
        null),

       (DEFAULT,
        'Dans cette bière de couleur ambrée, vous pouvez goûter des notes de caramel et d''épices, ainsi qu''un goût fruité d''orange. Elle est douce, sucrée et légèrement amère, et elle est appréciée par beaucoup.',
        'In this amber-coloured beer you can taste toffee and spicy tones, together with an orange-like fruitiness. It is soft, sweet and slightly bitter, and it’s loved by many.',
        null),

       (DEFAULT,
        'C''est vraiment une Tripel fantastique, pleine de délicieux arômes fruités de banane et de poire avec une certaine touche épicée. La bière est également assez houblonnée, ce qui s''équilibre parfaitement avec son corps ferme et sa douceur.',
        'It truly is a fantastic Tripel, full of yummy fruit aromas of banana and pear with a certain spicy touch. The beer is also quite hopped, which balances beautifully with the firm body and sweetness.',
        null),

       (DEFAULT,
        'Cette bière forte et brune est vraiment une bière à déguster tranquillement. Elle a une couleur plus fauve que son homologue. Elle possède une sécheresse très riche, comme celle d''un gâteau, qui donne un équilibre aux notes finales.',
        'This strong, dark beer is really one to enjoy quietly. It has a tawnier colour than its counterpart. It has a very rich dryness, like that of a cake, which gives a balanced finish to the final notes.',
        null),

       (DEFAULT,
        'La bière elle-même est séduisante avec sa couleur dorée et sa mousse ferme. Ce que beaucoup de gens remarquent d''abord, ce sont les notes de coriandre, d''écorce d''orange et de mandarine. Son goût est agréablement doux, mais fruité et frais. La finale est douce et un peu épicée, exactement comme vous voulez que cette bière se termine.',
        'The beer itself looks seductive with its golden colour and firm head. What many people notice first are the notes of coriander, orange peel and mandarin. It tastes pleasantly sweet, but fruity and fresh. The finish is soft and a little spicy, just how you want this beer to end.',
        null),

       (DEFAULT,
        'La Troubadour Magma possède les arômes fruités typiques d''une IPA, comme le fruit de la passion, les agrumes et la mangue, joliment combinés à des arômes fruités de levure, de pomme et d''ananas. La saveur de malt de type biscuit vous rappellera une IPA, mais le corps et la quantité d''alcool (9%) sont plus typiques d''une tripel.',
        'Troubadour Magma has the typical fruit flavours of an IPA, like passion fruit, citrus and mango, nicely combined with fruity yeast flavours of apple and pineapple. The biscuit-like malt flavour will remind you of an IPA, but the body and amount of alcohol (9%) is more typical of a tripel.',
        null),

       (DEFAULT,
        'Un jeune Orval est encore un peu sucré et houblonné. Avec le temps, cette trappiste devient plus sèche, plus pétillante et plus complexe. Une note acidulée se développe avec des arômes typiques de Brett, que l''on peut décrire comme de la basse-cour ou une couverture de cheval.',
        'A young Orval is still a bit sweet and hoppy. Over time, this trappist becomes dryer, more sparkling and more complex. A sour note develops with typical Brett aromas, which are best described as farmyard or a horse blanket.',
        null),

       (DEFAULT, 'Ressource non trouvée', 'Resource not found', 'not_found'),
       (DEFAULT, 'Veuillez fournir un numéro valide', 'Please provide a valid number', 'number_format');

INSERT INTO beer_types (id, name, color)
VALUES (DEFAULT, 'Wheat', '#FFD978'),
       (DEFAULT, 'Pale Ale', '#FFBE45'),
       (DEFAULT, 'India Pale Ale', '#F4AA00'),
       (DEFAULT, 'Bitter', '#DF7D01'),
       (DEFAULT, 'Amber Ale', '#B14305'),
       (DEFAULT, 'Irish Red Ale', '#BC3431'),
       (DEFAULT, 'Barley Wine', '#A63D02'),
       (DEFAULT, 'Brown Ale', '#9C3200'),
       (DEFAULT, 'Mild Ale', '#E79007'),
       (DEFAULT, 'Stout', '#35090A'),
       (DEFAULT, 'Porter', '#480601'),
       (DEFAULT, 'Scotch Ale', '#7F1903'),
       (DEFAULT, 'Old Ale', '#A03700'),
       (DEFAULT, 'Belgian Ales', '#CC6200'),
       (DEFAULT, 'Blond Ale', '#FCB123'),
       (DEFAULT, 'Saison', '#E28800'),
       (DEFAULT, 'Dubbel', '#D06B00'),
       (DEFAULT, 'Tripel', '#FBA401'),
       (DEFAULT, 'Pale Lager', '#FFC146'),
       (DEFAULT, 'Light Lager', '#FDD979'),
       (DEFAULT, 'Pilsner', '#FAC145'),
       (DEFAULT, 'Dortmunder', '#F9A700'),
       (DEFAULT, 'Munich Helles', '#FFBE41'),
       (DEFAULT, 'Amber Lager', '#D06A00'),
       (DEFAULT, 'Vienna Lager', '#D26407'),
       (DEFAULT, 'Oktoberfest', '#F9990C'),
       (DEFAULT, 'Rauchbier', '#902704'),
       (DEFAULT, 'Bock', '#992C02'),
       (DEFAULT, 'Traditional Bock', '#A63E01'),
       (DEFAULT, 'Maibock', '#E48601'),
       (DEFAULT, 'Doppelbock', '#842300'),
       (DEFAULT, 'Eisbock', '#650804'),
       (DEFAULT, 'Dark Lager', '#8D2B00'),
       (DEFAULT, 'Schwarzbier', '#57090C'),
       (DEFAULT, 'Munich Dunkel', '#6D0F03'),
       (DEFAULT, 'Lambic', '#9D1104'),
       (DEFAULT, 'Gueuze', '#F59C00'),
       (DEFAULT, 'Faro', '#9C3103'),
       (DEFAULT, 'Fruit Lambic', '#A72328'),
       (DEFAULT, 'Kriek', '#B82A29');

INSERT INTO cities (id, name)
VALUES (DEFAULT, 'Brussels'),
       (DEFAULT, 'Antwerp'),
       (DEFAULT, 'Brugge'),
       (DEFAULT, 'Izegem'),
       (DEFAULT, 'Eizeringen'),
       (DEFAULT, 'Sint-Truiden'),
       (DEFAULT, 'Denderleeuw'),
       (DEFAULT, 'Oostvleteren');

INSERT INTO places (id, name, type, address, url, city_id, created_at)
VALUES (DEFAULT, 'Kulminator', 'Bar', '32 Vleminckveld', 'https://www.facebook.com/Kulminator.friends/', 2, DEFAULT),
       (DEFAULT, 'Brugs Beertje', 'Bar', 'Kemelstraat 5', 'https://www.brugsbeertje.be/en/home-2/', 3, DEFAULT),
       (DEFAULT, 'A La Becasse', 'Bar', 'off 11 Rue Tabora', 'https://alabecasse.be', 1, DEFAULT),
       (DEFAULT, 'T Kroegske', 'Bar', '35 Vijfwegenstraat', 'http://www.kroegske.nl/', 4, DEFAULT),
       (DEFAULT, 'Grote Dorst', 'Bar', 'Frans Baetensstraat 45', 'http://www.dorst.be/en/welcome', 5, DEFAULT),
       (DEFAULT, 'De Gebrande Winning', 'Restaurant', 'Zepperenweg 7', 'http://degebrandewinning.be/', 6, DEFAULT),
       (DEFAULT, 'De Heeren van Liedekercke', 'Restaurant', 'Kasteelstraat 33', 'http://www.heerenvanliedekercke.be/', 7, DEFAULT),
       (DEFAULT, 'Het Oude Schooltje - Struise Brouwers @ The Old School', 'Brewery', 'Kasteelstraat 50',
        'http://www.struisebrouwers.com/', 8, DEFAULT),
       (DEFAULT, 'Cantillon Brewery/Museum', 'Brewery', '56 rue Gheude', 'http://www.cantillon.be/', 1, DEFAULT),
       (DEFAULT, '2be Beer', 'Shop', 'Wollestraat 53', 'https://www.2-be.biz/', 3, DEFAULT);



INSERT INTO beers (id, name, image_src, beer_type, description, abv, created_at)
VALUES (DEFAULT, 'Tripel Karmeliet', 'tripel-karmeliet.png', 18, (SELECT id FROM translations WHERE id = 1), 8.4,
        DEFAULT),
       (DEFAULT, 'Affligem Blond', 'affligem_blond_2.png', 15, (SELECT id FROM translations WHERE id = 2), 6.8,
        DEFAULT),
       (DEFAULT, 'Chimay Blue', 'chimay---blauw_v2.png', 14, (SELECT id FROM translations WHERE id = 3), 9, DEFAULT),
       (DEFAULT, 'Duvel', 'duvel.png', 2, (SELECT id FROM translations WHERE id = 4), 8.5, DEFAULT),
       (DEFAULT, 'Pauwel Kwak', 'pauwel---kwak.png', 14, (SELECT id FROM translations WHERE id = 5), 8.4, DEFAULT),
       (DEFAULT, 'Westmalle Tripel', 'westmalle-tripel.png', 18, (SELECT id FROM translations WHERE id = 6), 9.5,
        DEFAULT),
       (DEFAULT, 'Rochefort 8', 'rochefort---8_v2.png', 13, (SELECT id FROM translations WHERE id = 7), 9.2, DEFAULT),
       (DEFAULT, 'La Chouffe Blonde D''ardenne', 'la-chouffe---blonde_v2.png', 2,
        (SELECT id FROM translations WHERE id = 8), 8, DEFAULT),
       (DEFAULT, 'Troubadour Magma', 'troubadour-magma.png', 3, (SELECT id FROM translations WHERE id = 9), 9, DEFAULT),
       (DEFAULT, 'Orval', 'orval.png', 2, (SELECT id FROM translations WHERE id = 10), 6.2, DEFAULT);


INSERT INTO beer_places (id, beer_id, place_id)
VALUES (DEFAULT, 1, 3),
       (DEFAULT, 1, 5),
       (DEFAULT, 1, 8),
       (DEFAULT, 1, 10),
       (DEFAULT, 2, 2),
       (DEFAULT, 2, 6),
       (DEFAULT, 2, 8),
       (DEFAULT, 2, 9),
       (DEFAULT, 2, 10),
       (DEFAULT, 3, 1),
       (DEFAULT, 3, 5),
       (DEFAULT, 3, 8),
       (DEFAULT, 3, 9),
       (DEFAULT, 3, 10),
       (DEFAULT, 4, 2),
       (DEFAULT, 4, 8),
       (DEFAULT, 4, 10),
       (DEFAULT, 5, 4),
       (DEFAULT, 5, 5),
       (DEFAULT, 5, 7),
       (DEFAULT, 5, 8),
       (DEFAULT, 5, 10),
       (DEFAULT, 6, 1),
       (DEFAULT, 6, 4),
       (DEFAULT, 6, 7),
       (DEFAULT, 6, 10),
       (DEFAULT, 7, 4),
       (DEFAULT, 7, 5),
       (DEFAULT, 7, 9),
       (DEFAULT, 7, 10),
       (DEFAULT, 7, 10),
       (DEFAULT, 8, 2),
       (DEFAULT, 8, 6),
       (DEFAULT, 8, 8),
       (DEFAULT, 8, 9),
       (DEFAULT, 8, 10),
       (DEFAULT, 9, 1),
       (DEFAULT, 9, 10),
       (DEFAULT, 10, 3),
       (DEFAULT, 10, 7),
       (DEFAULT, 10, 10);


INSERT INTO beer_places (id, place_id, beer_id)
VALUES (DEFAULT, 1, 3),
       (DEFAULT, 1, 6),
       (DEFAULT, 1, 9),
       (DEFAULT, 2, 2),
       (DEFAULT, 2, 4),
       (DEFAULT, 2, 8),
       (DEFAULT, 3, 1),
       (DEFAULT, 3, 10),
       (DEFAULT, 4, 5),
       (DEFAULT, 4, 6),
       (DEFAULT, 4, 7),
       (DEFAULT, 4, 8),
       (DEFAULT, 5, 1),
       (DEFAULT, 5, 3),
       (DEFAULT, 5, 5),
       (DEFAULT, 5, 7),
       (DEFAULT, 6, 2),
       (DEFAULT, 7, 5),
       (DEFAULT, 7, 6),
       (DEFAULT, 7, 10),
       (DEFAULT, 8, 1),
       (DEFAULT, 8, 2),
       (DEFAULT, 8, 3),
       (DEFAULT, 8, 4),
       (DEFAULT, 8, 5),
       (DEFAULT, 9, 2),
       (DEFAULT, 9, 3),
       (DEFAULT, 9, 7),
       (DEFAULT, 9, 8),
       (DEFAULT, 10, 1),
       (DEFAULT, 10, 2),
       (DEFAULT, 10, 3),
       (DEFAULT, 10, 4),
       (DEFAULT, 10, 5),
       (DEFAULT, 10, 6),
       (DEFAULT, 10, 7),
       (DEFAULT, 10, 8),
       (DEFAULT, 10, 9),
       (DEFAULT, 10, 10);
